# Generated by Django 3.1.2 on 2021-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SR',
            fields=[
                ('sr_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
