# Generated by Django 3.1.2 on 2021-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_srfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srfiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='srfiles',
            name='fileId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
